//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsmBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountItems
    {
        public AccountItems()
        {
            this.ledger = new HashSet<ledger>();
            this.Dues = new HashSet<Dues>();
            this.Dues1 = new HashSet<Dues>();
            this.journals = new HashSet<journals>();
            this.journals1 = new HashSet<journals>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public int Ledger_Id { get; set; }
        public string Description { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public double Balance { get; set; }
        public Nullable<bool> ControlAC { get; set; }
        public string Ref { get; set; }
        public string Status { get; set; }
    
        public virtual NominalLedger NominalLedger { get; set; }
        public virtual ICollection<ledger> ledger { get; set; }
        public virtual ICollection<Dues> Dues { get; set; }
        public virtual ICollection<Dues> Dues1 { get; set; }
        public virtual ICollection<journals> journals { get; set; }
        public virtual ICollection<journals> journals1 { get; set; }
    }
}
