//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsmBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dues
    {
        public Dues()
        {
            this.journals = new HashSet<journals>();
            this.Transactions = new HashSet<Transactions>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public bool IsMonthly { get; set; }
        public int drAC { get; set; }
        public int crAC { get; set; }
        public string Source { get; set; }
    
        public virtual AccountItems AccountItems { get; set; }
        public virtual AccountItems AccountItems1 { get; set; }
        public virtual ICollection<journals> journals { get; set; }
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}
