//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsmBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class journals
    {
        public journals()
        {
            this.ledger = new HashSet<ledger>();
            this.Transactions = new HashSet<Transactions>();
        }
    
        public int id { get; set; }
        public string Narration { get; set; }
        public System.DateTime transdate { get; set; }
        public int ticketno { get; set; }
        public int refticketno { get; set; }
        public int DrAC { get; set; }
        public int CrAC { get; set; }
        public decimal Amount { get; set; }
        public int journaltype_id { get; set; }
        public int User_Id { get; set; }
    
        public virtual AccountItems AccountItems { get; set; }
        public virtual AccountItems AccountItems1 { get; set; }
        public virtual Dues Dues { get; set; }
        public virtual tickets tickets { get; set; }
        public virtual tickets tickets1 { get; set; }
        public virtual ICollection<ledger> ledger { get; set; }
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}
