//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsmBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ledger
    {
        public int id { get; set; }
        public int Ticket_id { get; set; }
        public int Account_id { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
        public System.DateTime transdate { get; set; }
        public int User_Id { get; set; }
        public int journal_id { get; set; }
    
        public virtual AccountItems AccountItems { get; set; }
        public virtual tickets tickets { get; set; }
        public virtual journals journals { get; set; }
    }
}
