//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsmBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominalLedger
    {
        public NominalLedger()
        {
            this.AccountItems = new HashSet<AccountItems>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public int LastCode { get; set; }
        public int Intervals { get; set; }
        public int AccountType_id { get; set; }
        public int PLItem_id { get; set; }
    
        public virtual ICollection<AccountItems> AccountItems { get; set; }
        public virtual AccountTypes AccountTypes { get; set; }
        public virtual PLItems PLItems { get; set; }
    }
}
