//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsmBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tickets
    {
        public tickets()
        {
            this.ledger = new HashSet<ledger>();
            this.journals = new HashSet<journals>();
            this.journals1 = new HashSet<journals>();
        }
    
        public int id { get; set; }
        public string TicketNo { get; set; }
    
        public virtual ICollection<ledger> ledger { get; set; }
        public virtual ICollection<journals> journals { get; set; }
        public virtual ICollection<journals> journals1 { get; set; }
    }
}
