//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsmBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int id { get; set; }
        public int Member_id { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Date { get; set; }
        public int Due_id { get; set; }
        public int journal_id { get; set; }
        public string Narration { get; set; }
    
        public virtual Dues Dues { get; set; }
        public virtual journals journals { get; set; }
        public virtual Members Members { get; set; }
        public virtual MonthlyDues MonthlyDues { get; set; }
    }
}
