//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsmBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendors
    {
        public int id { get; set; }
        public string Fullname { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string eMail { get; set; }
        public string BBMPin { get; set; }
        public string BankAC { get; set; }
        public Nullable<int> PayableAC { get; set; }
        public Nullable<int> ReceivableAC { get; set; }
        public Nullable<int> ExpenseAC { get; set; }
        public string photo { get; set; }
    }
}
